---
title: "Classification of firm growth"
format: 
  pdf:
    geometry:
      - top = 20mm
      - left= 20mm
      - right=20mm
    fontsize: 10pt
    fig-pos: H
editor: source
author: "Anja Hahn, Teresa Hübel, Anne Valder"
---

# Abstract


{{< pagebreak >}}

## xxxx



```{r}
############################################
# Load libraries and set global options
############################################
knitr::opts_chunk$set(include = FALSE, fig.align = 'center', cache = TRUE,
                      warning = FALSE, message = FALSE, echo = FALSE)

rm(list=ls())
# libraries
library(data.table)
library(tidyverse)
library(skimr)
library(caret)
library(randomForest)
library(gbm)
library(knitr)

options(digits = 3)
color <- c("#00AFBB", "#E7B800", "#D55E00", "#009E73", "#CC79A7")
```



```{r}
############################################
# Load data
############################################



```

```{r}
############################################
# First Look at data
############################################

```

```{r}
############################################
# Data preparation
############################################

```


```{r}
############################################
# Define Target
############################################

```

```{r}
############################################
# Feature Engineering
############################################

```

```{r}
############################################
# Prepare Cross Validation
############################################
# partition into train and test set


# set up 5-fold cross validation

```

```{r}
############################################
# Prepare Model Comparison
############################################
# Prepare functions to do AUC and ROC of each model
# Prepare how to save 5-CV RMSE for each model

```

```{r}
```



```{r}
############################################
# Probability prediction - Model 1: Logit
############################################

```

```{r}
############################################
# Probability prediction - Model 2: Random Forest
############################################

```

```{r}
############################################
# Probability prediction - Model 3: ? (Maybe Classification tree?)
############################################

```

```{r}
############################################
# Model Selection
############################################

# how do I select the best model without yet classifying?

```


```{r}
############################################
# Classification - Definition of loss function
############################################
# Define cost forFP and FN
# Calculate the prevalence of cases in the population
```

```{r}

```

